server:
  port: 7585
  servlet:
    #这里一定要配置，否则本地IP访问授权会不成
    context-path: /sso


spring:
  application:
    name: cloud-auth-service

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
      # 是否从其他的服务中心同步服务列表
      fetch-registry: true
      # 是否把自己作为服务注册到其他服务注册中心
      register-with-eureka: false

logging:
  level:
    root: debug



