server:
  port: 8999

spring:
  application:
    name: sleuth-zipkin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.20.101:9411/
    discoveryClientEnabled: false