server:
  port: 7589
  session:
    cookie:
      name: CLIENT-SESSIONID
spring:
  application:
    name: cloud-auth-client

auth-server: http://localhost:7585
security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
      scope: all


logging:
  level:
    root: debug
