server:
  port: 8986

spring:
  application:
    name: cloud-jdbc



##数据库ds0
  datasource:
    ds0:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3396/demo0?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=Asia/Shanghai
      ##jdbcUrl: jdbc:mysql://127.0.0.1:3396/demo0?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initialize: false
      sqlScriptEncoding: UTF-8
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 600000
      minEvictableIdleTimeMillis: 3000000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true  #在检查闲置连接时同时检查连接可用性
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,logback
  ##数据库ds1
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3396/demo1?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=Asia/Shanghai
      ##jdbcUrl: jdbc:mysql://127.0.0.1:3396/demo1?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initialize: false
      sqlScriptEncoding: UTF-8
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 600000
      minEvictableIdleTimeMillis: 3000000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true  #在检查闲置连接时同时检查连接可用性
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,logback
    
##mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/**/*Mapper.xml
  type-aliases-package: com.some.jdbc.domain
  # 数据库相关配置
  global-config:
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: ID_WORKER
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: not_empty
    #驼峰下划线转换
    column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    db-type: mysql
  
  #刷新mapper 调试神器
  refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



